
"""
Macro Cycle Lab - Taiwan Weight Backtest
Purpose:
- Macro layer = NDC-heavy composite using 1M/3M dual momentum
- Market layer = TAIEX trend/momentum confirmation
- Sweep Macro/Market weights: 80/20, 75/25, 70/30, 65/35
- Use train / validation / out-of-sample split
"""

from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

INPUT = Path("data/processed/taiwan_macro_inputs.csv")
NDC_XLSX = Path("data/raw/ndc_business_cycle.xlsx")
OUTPUT = Path("data/processed/taiwan_weight_backtest.csv")

def rolling_z(s, window=60, min_periods=24):
    mean = s.shift(1).rolling(window, min_periods=min_periods).mean()
    std = s.shift(1).rolling(window, min_periods=min_periods).std()
    return (s - mean) / std

def load_ndc(path):
    raw = pd.read_excel(path, sheet_name=0)
    raw = raw.iloc[1:].copy()
    raw["date"] = pd.to_datetime(raw.iloc[:,0], errors="coerce")

    name_map = {}
    for c in raw.columns:
        s = str(c)
        if "景氣對策信號(分)" in s:
            name_map[c] = "ndc_score"
        elif "領先指標不含趨勢" in s:
            name_map[c] = "ndc_leading"
        elif "同時指標不含趨勢" in s:
            name_map[c] = "ndc_coincident"

    raw = raw.rename(columns=name_map)
    cols = ["date","ndc_score","ndc_leading","ndc_coincident"]
    out = raw[[c for c in cols if c in raw.columns]].copy()
    for c in out.columns:
        if c != "date":
            out[c] = pd.to_numeric(out[c], errors="coerce")
    return out

def build_macro_layer(df):
    bases = {
        "ndc": "ndc_leading",
        "orders_total": "export_orders_total_usd_mn",
        "orders_elec": "export_orders_electronics_usd_mn",
        "orders_ict": "export_orders_ict_usd_mn",
        "mfg_elec": "mfg_info_electronics_index",
    }

    # NDC-heavy weights found strongest in first-stage test
    factor_w = {
        "ndc": 0.50,
        "orders_total": 0.20,
        "orders_elec": 0.10,
        "orders_ict": 0.10,
        "mfg_elec": 0.10,
    }

    for h in [1,3]:
        for key,col in bases.items():
            mom = pd.to_numeric(df[col], errors="coerce").pct_change(h) * 100
            df[f"{key}_z{h}"] = rolling_z(mom)

        df[f"macro_{h}m"] = sum(
            factor_w[k] * df[f"{k}_z{h}"] for k in factor_w
        )

    # Dual momentum: 40% fast + 60% stable
    df["macro_score"] = 0.40*df["macro_1m"] + 0.60*df["macro_3m"]
    return df

def build_market_layer(df):
    # Use only information available at that date.
    # These columns are generated by fetch_taiwan_full.py.
    raw_market = pd.DataFrame(index=df.index)

    raw_market["m3"] = pd.to_numeric(df["taiex_return_3m_pct"], errors="coerce")
    raw_market["m6"] = pd.to_numeric(df["taiex_return_6m_pct"], errors="coerce")
    raw_market["ma6"] = pd.to_numeric(df["taiex_vs_ma_6m_pct"], errors="coerce")
    raw_market["ma12"] = pd.to_numeric(df["taiex_vs_ma_12m_pct"], errors="coerce")

    for c in raw_market.columns:
        df[f"market_{c}_z"] = rolling_z(raw_market[c])

    # Equal market confirmation components initially.
    df["market_score"] = (
        0.25*df["market_m3_z"] +
        0.25*df["market_m6_z"] +
        0.25*df["market_ma6_z"] +
        0.25*df["market_ma12_z"]
    )
    return df

def evaluate(df, score_col, start, end):
    d = df[(df["date"] >= start) & (df["date"] <= end)][
        [score_col,"future6_coincident_pct","downturn6"]
    ].dropna()

    if len(d) < 12:
        return np.nan, np.nan, len(d)

    auc = (
        roc_auc_score(d["downturn6"], -d[score_col])
        if d["downturn6"].nunique() > 1
        else np.nan
    )
    corr = d[score_col].corr(d["future6_coincident_pct"], method="spearman")
    return auc, corr, len(d)

def main():
    macro = pd.read_csv(INPUT, parse_dates=["date"])
    ndc = load_ndc(NDC_XLSX)

    df = ndc.merge(macro, on="date", how="inner")
    df = df[(df["date"] >= "2000-01-01")].sort_values("date").copy()

    needed_market = [
        "taiex_return_3m_pct","taiex_return_6m_pct",
        "taiex_vs_ma_6m_pct","taiex_vs_ma_12m_pct"
    ]
    missing = [c for c in needed_market if c not in df.columns]
    if missing:
        raise RuntimeError(
            "TAIEX market columns missing. Run fetch_taiwan_full.py first. "
            f"Missing: {missing}"
        )

    df = build_macro_layer(df)
    df = build_market_layer(df)

    df["future6_coincident_pct"] = (
        df["ndc_coincident"].shift(-6) / df["ndc_coincident"] - 1
    ) * 100
    df["downturn6"] = (df["future6_coincident_pct"] < 0).astype(int)

    splits = {
        "train_2000_2015": ("2000-01-01","2015-12-01"),
        "validation_2016_2020": ("2016-01-01","2020-12-01"),
        "test_2021_latest": ("2021-01-01","2099-12-01"),
    }

    mixes = {
        "80_20": (0.80,0.20),
        "75_25": (0.75,0.25),
        "70_30": (0.70,0.30),
        "65_35": (0.65,0.35),
    }

    rows = []
    for label,(mw,sw) in mixes.items():
        col = f"combined_{label}"
        df[col] = mw*df["macro_score"] + sw*df["market_score"]

        row = {
            "mix": label,
            "macro_weight": mw,
            "market_weight": sw,
        }
        aucs = []
        for split,(start,end) in splits.items():
            auc,corr,n = evaluate(df,col,start,end)
            row[f"{split}_auc"] = auc
            row[f"{split}_spearman"] = corr
            row[f"{split}_n"] = n
            aucs.append(auc)

        row["robust_score"] = (
            0.25*aucs[0] +
            0.35*aucs[1] +
            0.40*aucs[2] -
            0.15*np.nanstd(aucs)
        )
        rows.append(row)

    result = pd.DataFrame(rows).sort_values("robust_score", ascending=False)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(OUTPUT, index=False, encoding="utf-8-sig")

    print(result.round(4).to_string(index=False))
    print("\nBest mix:", result.iloc[0]["mix"])
    print("Saved:", OUTPUT)

if __name__ == "__main__":
    main()
